import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Providers } from "./providers";

import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Next Notes",
	description: "Generated by create next app",
};

const montserrat = Montserrat({
	subsets: ["latin"],
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${montserrat.className} antialiased `}>
				<ThemeProvider attribute="class">
					<Providers>
						<Header />
						{children}
						<Toaster
							toastOptions={{
								className:
									"bg-white ring-1 ring-black dark:bg-black dark:text-white",
							}}
						/>
					</Providers>
				</ThemeProvider>
			</body>
		</html>
	);
}
